install some dependencies
See https://github.com/elastic/apm-agent-python/issues/1660

it might be solved...

diff --git a/.k8s/Dockerfile b/.k8s/Dockerfile
--- a/.k8s/Dockerfile
+++ b/.k8s/Dockerfile
@@ -12,5 +12,27 @@ RUN apt-get -qq update && apt-get -qq -y --no-install-recommends install \
     make \
     gnupg2 && \
     rm -rf /var/lib/apt/lists/*
+
+# connection to ha.pool.sks-keyservers.net fails sometimes, so let's retry with couple different servers
+RUN for server in $(shuf -e ha.pool.sks-keyservers.net \
+                            hkp://p80.pool.sks-keyservers.net:80 \
+                            keyserver.ubuntu.com \
+                            hkp://keyserver.ubuntu.com:80 \
+                            pgp.mit.edu) ; do gpg --no-tty --keyserver "$server" --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 && s=0 && break || s=$?; done; (exit $s)
+
+RUN curl -o /usr/local/bin/gosu -sSL "https://github.com/tianon/gosu/releases/download/1.10/gosu-$(dpkg --print-architecture)" \
+    && curl -o /usr/local/bin/gosu.asc -sSL "https://github.com/tianon/gosu/releases/download/1.10/gosu-$(dpkg --print-architecture).asc" \
+    && gpg --verify /usr/local/bin/gosu.asc \
+    && rm /usr/local/bin/gosu.asc \
+    && chmod +x /usr/local/bin/gosu
+
 WORKDIR /code
 ADD . .
+COPY tests/entrypoint.sh /usr/local/bin/entrypoint.sh
+
+# pre-install base requirements
+RUN python -m pip install --progress-bar off -U pip && pip install --progress-bar off -r tests/requirements/reqs-base.txt
+
+RUN chmod +x /usr/local/bin/entrypoint.sh
+
+ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
